 SELECT 
    FLEXA.RBUKRS                                      AS "company_code"
   ,FLEXA.RLDNR                                       AS "ledger"
   ,FLEXA.GJAHR                                       AS "fiscal_year"
   ,FLEXA.POPER                                       AS "fiscal_month"
   ,FLEXA.RYEAR                                       AS "year"
   ,FLEXA.RACCT                                       AS "gl_account"
   ,FLEXA.RCNTR                                       AS "cost_center"
   ,FLEXA.ZZCUSTGRP                                   AS "customer_group"
   ,FLEXA.BUDAT                                       AS "posting_date"
   ,FLEXA.DOCNR                                       AS "document_number"
   ,FLEXA.BUZEI                                       AS "documnet_line"
   ,FLEXA.DOCLN                                       AS "document_line_2"
   ,FLEXA.DRCRK                                       AS "debit_credit"
   ,FLEXA.MSL                                         AS "quantity"
   ,ROUND(CAST(FLEXA.WSL AS FLOAT),2)                 AS "value_transaction_currency"
   ,ROUND(CAST(FLEXA.HSL AS FLOAT),2)                 AS "value_currency"
   ,COALESCE(FLEXA.RACCT, 'No GL')                    AS "account"
   ,FLEXA.COST_ELEM                                   AS "cost_element"
   ,FLEXA.PRCTR                                       AS "profit_center"
   ,FLEXA.PPRCTR                                      AS "partner_profit_center"
FROM {{source('sap_ecc', 'src_sap_ecc__faglflexa')}} AS FLEXA 
