SELECT 
     MARA.MATNR                      AS "material"
    ,MARA.ZZMODEL_MAIN               AS "model"
    ,MARA.MTART                      AS "material_manufacturing_type"
    ,MARA.MBRSH                      AS "material_industry_selector"
    ,MARA.MATKL                      AS "material_group"
    ,MARA.BISMT                      AS "material_product_initialization_request__code"
    ,MARA.LABOR                      AS "material_designed"
    ,MARA.EKWSL                      AS "purchasing_value_key"
    ,MARA.DISST                      AS "material_low_level_code"
    ,MARA.TRAGR                      AS "material_transportation_group"
    ,CAST(MARA.EAN11 AS  VARCHAR)    AS "material_upc"
    ,MARA.NUMTP                      AS "material_upc_category"
    ,MARA.PRDHA                      AS "material_product_hierarchy"
    {{ get_product_hierarchy_levels('PRDHA', 'MARA', 38) }}
    ,MARA.EXTWG                      AS "material_external_group"
    ,MARA.MSTAE                      AS "cross_plant_material_status"
    ,MARA.ZZMFRGR                    AS "material_freight_group"
    ,MARA.ZZMFRCL                    AS "material_freight_class"
    ,MARA.ZZMFRDES                   AS "material_freight_description"
    ,MARA.ZZPRIHTS_US                AS "hts_code"
    ,MARA.LVORM = 'X'                AS "is_material_no_longer_valid"
    ,MARA.ERSDA                      AS "created_on"
    ,MARA.ERNAM                      AS "created_by"
    ,MARA.LAEDA                      AS "changed_on"
    ,MARA.AENAM                      AS "changed_by"
    ,MARA.VPSTA                      AS "completed_status"
    ,MARA.PSTAT                      AS "maintance_status"
    ,MARA.SOURCE                     AS "source"
    ,MARA.RUN_DATE_TIME_VAR          AS "uploaded_as_of_date_time"
FROM {{source('sap_ecc', 'src_sap_ecc__mara')}} AS MARA
