SELECT DISTINCT
     MARC.werks                                     AS "plant"
    ,MARC.matnr                                     AS "material"
    ,MARC.herkl                                     AS "country_of_origin"
    ,MARC.mmsta                                     AS "plant_material_status"
    ,MARC.mmstd                                     AS "plant_material_active_date"
    ,MARC.ausdt                                     AS "effective_out_date"
    ,MARC.kzaus                                     AS "discontinuation_indicator"
    ,MARC.ekgrp                                     AS "purchasing_group"
    ,MARC.dispr                                     AS "mrp_profile"
    ,MARC.dismm                                     AS "mrp_type"
    ,MARC.dispo                                     AS "mrp_planner"
    ,MARC.miskz                                     AS "mrp_mixed_indicator"
    ,MARC.shzet                                     AS "safety_time"
    ,MARC.plifz                                     AS "planned_delivery_duration" 
    ,MARC.ausme                                     AS "unit_of_issue"
    ,MARC.beskz                                     AS "procurment_type"
    ,MARC.disls                                     AS "lot_size"
    ,CAST(MARC.bstfe AS INT)                        AS "fixed_lot_size"
    ,CAST(MARC.bstmi AS INT)                        AS "minimum_lot_size"
    ,CAST(MARC.bstma AS INT)                        AS "maximum_lot_size"
    ,MARC.disls                                     AS "lot_size_type"
    ,CAST(MARC.minbe AS INT)                        AS "reorder_point"
    ,CAST(MARC.eisbe AS INT)                        AS "safety_stock"
    ,CAST(MARC.bstrf AS INT)                        AS "rounding_value"
    ,MARC.ZZADDTL_CATG1                             AS "service_level_category"
    ,MARC.ZZADDTL_CATG2                             AS "customer_merchant_department"
    ,MARC.ZZADDTL_CATG3                             AS "customer_merchant_department_class"
    ,MARC.LFRHY                                     AS "planning_cycle"
    ,MARC.FXHOR                                     AS "planning_time_fence"
    ,MARC.DISPO                                     AS "mrp_controller"
    ,MARC.EISLO                                     AS "min_safety_stock"
    ,MARC.SHFLG                                     AS "safety_time_indicators"
    ,MARC.SHPRO                                     AS "stime_period_profile"
    ,MARC.LGRAD                                     AS "service_level_perc"
    ,MARC.RWPRO                                     AS "coverage_profile"
    ,MARC.PERKZ                                     AS "period_indicator"
    ,MARC.STRGR                                     AS "strategy_group"
    ,MARC.VRMOD                                     AS "consumption_mode"
    ,MARC.VINT2                                     AS "fwd_consumption_period"
    ,MARC.VINT1                                     AS "bwd_consumption_period"
FROM {{ source('sap_ecc','src_sap_ecc__marc') }} AS MARC
