## Project
name: cch_dbt_poc
version: "1.0"
config-version: 2
profile: cch

## Sources
model-paths: [models]
analysis-paths: [analysis]
test-paths: [tests]
seed-paths: [seeds]
macro-paths: [macros]
snapshot-paths: [snapshots]

## Target
target-path: target
clean-targets: [target, dbt_modules]

## Variables
vars:
  cch_valid_company: "'1400', '1300', '1600', '1800', '1950', '1200', '1700'"
  return_types: "'RE', 'ZS2', 'ZM4'"
  man_sales_types: "'ZM6', 'ZM1'"
  mat_cogs_types: "'Z2'"

## Models
models:
  cch_dbt_poc:
    int:
      +materialized: ephemeral
    staging:
      +materialized: view
    marts:
      +materialized: view
