SELECT 
     AM.COD_CONTO               AS "account"
    ,AM.DESC_CONTO0             AS "account_description"
    ,AM.DESC_CONTO1             AS "account_description_1"
    ,AM.DESC_CONTO2             AS "account_description_2"
    ,AM.DESC_CONTO3             AS "account_description_3"
    ,AM.COD_CONTO_GERARCHIA     AS "hearchy_account_code"
    ,AM.COD_CONTO_ELEGER1       AS "choice_account_1_code"
    ,AM.DESC_CONTO_ELEGER1      AS "choice_account_1_description"
    ,AM.COD_CONTO_ELEGER2       AS "account_sub_group_code"
    ,AM.DESC_CONTO_ELEGER2      AS "account_sub_group"
    ,AM.COD_CONTO_ELEGER3       AS "account_group_code"
    ,AM.DESC_CONTO_ELEGER3      AS "account_group"
    ,AM.COD_CONTO_ELEGER4       AS "pl_account_code"
    ,AM.DESC_CONTO_ELEGER4      AS "pl_account"
    ,AM.COD_CONTO_ELEGER5       AS "pl_sub_category_code"
    ,AM.DESC_CONTO_ELEGER5      AS "pl_sub_category"
    ,AM.COD_CONTO_ELEGER6       AS "pl_category_code"
    ,AM.DESC_CONTO_ELEGER6      AS "pl_category"
    ,AM.COD_CONTO_ELEGER7       AS "choice_account_7_code"
    ,AM.DESC_CONTO_ELEGER7      AS "choice_account_7_description"
    ,AM.COD_CONTO_ELEGER8       AS "choice_account_8_code"
    ,AM.DESC_CONTO_ELEGER8      AS "choice_account_8_description"
FROM {{source('raw_cch','src_cch_account_master')}} AS AM
